In [1]:
from dataset import Dictionary, VQAFeatureDataset, VisualGenomeFeatureDataset
from dataset_gqa import GQAFeatureDataset
from dataset_gqa import tfidf_from_questions_gqa
from os.path import join, exists
import torch
import numpy as np

In [ ]:
dictionary = Dictionary.load_from_file(join('data', 'glove/dictionary.pkl'))
train_dset = GQAFeatureDataset('testdev_all', dictionary, 'semantic', adaptive=False, pos_emb_dim=64,dataroot='data')

In [2]:
dictionary = Dictionary.load_from_file(join('data', 'glove/dictionary.pkl'))
train_dset = VQAFeatureDataset('train', dictionary, 'semantic', adaptive=False, pos_emb_dim=64,dataroot='data')

loading dictionary from data/glove/dictionary.pkl
loading features from h5 file data/Bottom-up-features-fixed/train36.hdf5
Loaded semantic adj matrix from file... (82783, 36, 36)
Setting spatial adj matrix to None...


In [3]:
features, normalized_bb, question, target, question_id, image_id, bb, spatial_adj_matrix,semantic_adj_matrix = train_dset.__getitem__(100)

#{'question_id': 142001, 'image_id': 142, 'image': 6372, 'question': 'Is this a banana toast?', 'answer': {'labels': tensor([9, 3]), 'scores': tensor([1., 1.])}, 'q_token': tensor([    1,     2,    14,   352,   684, 19901, 19901, 19901, 19901, 19901,
#        19901, 19901, 19901, 19901])}

{'question_id': 142001, 'image_id': 142, 'image': 6372, 'question': 'Is this a banana toast?', 'answer': {'labels': tensor([9, 3]), 'scores': tensor([1., 1.])}, 'q_token': tensor([    1,     2,    14,   352,   684, 19901, 19901, 19901, 19901, 19901,
        19901, 19901, 19901, 19901])}


In [4]:
print (features)
print (features.shape)
#(100,2048)

tensor([[2.5822e-03, 8.8432e-01, 2.5149e-01,  ..., 0.0000e+00, 3.7400e+00,
         6.0698e+00],
        [3.2182e-02, 6.7804e+00, 1.5828e-01,  ..., 3.6700e-01, 1.7587e+01,
         9.4776e-01],
        [0.0000e+00, 1.2841e+00, 4.1078e-01,  ..., 2.6169e-03, 5.0143e+00,
         5.7377e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 1.0962e+00,
         5.6786e-04],
        [0.0000e+00, 1.9302e+00, 1.4887e-01,  ..., 0.0000e+00, 3.4882e-01,
         2.9126e-03],
        [0.0000e+00, 1.9552e+00, 2.7028e+00,  ..., 0.0000e+00, 1.5394e+00,
         0.0000e+00]])
torch.Size([36, 2048])


In [5]:
print (normalized_bb)
print (normalized_bb.shape)
#(2048,7,7)

tensor([[0.5958, 0.5996, 0.7637, 0.7143, 0.1679, 0.1147],
        [0.3612, 0.5827, 0.8140, 0.8695, 0.4528, 0.2868],
        [0.4487, 0.5912, 0.5865, 0.6646, 0.1378, 0.0734],
        [0.0932, 0.5768, 0.9983, 0.9988, 0.9051, 0.4219],
        [0.2918, 0.6015, 0.4582, 0.7191, 0.1664, 0.1176],
        [0.5684, 0.7244, 0.7827, 0.8625, 0.2142, 0.1381],
        [0.3095, 0.7556, 0.5284, 0.8928, 0.2189, 0.1372],
        [0.1481, 0.5881, 0.5616, 0.8599, 0.4135, 0.2719],
        [0.5546, 0.3001, 0.7995, 0.5200, 0.2449, 0.2199],
        [0.4593, 0.6647, 0.6364, 0.7905, 0.1771, 0.1258],
        [0.0000, 0.2714, 0.9983, 0.9175, 0.9983, 0.6462],
        [0.2505, 0.7084, 0.4235, 0.7887, 0.1730, 0.0804],
        [0.5399, 0.1192, 0.8700, 0.2538, 0.3301, 0.1346],
        [0.9086, 0.7312, 0.9983, 0.9988, 0.0897, 0.2676],
        [0.2620, 0.2803, 0.5316, 0.5566, 0.2697, 0.2763],
        [0.5200, 0.1185, 0.9075, 0.4393, 0.3875, 0.3208],
        [0.5986, 0.3447, 0.7918, 0.3970, 0.1931, 0.0523],
        [0.287

In [ ]:
print (question)
print (question.shape)

In [ ]:
print (target)
print (target.shape)

In [ ]:
print (question_id)

In [ ]:
print (image_id)

In [6]:
print (bb)
print (bb.shape)
#(100,4)

tensor([[285.9700, 383.7222, 366.5641, 457.1535],
        [173.3700, 372.9434, 390.7298, 556.5077],
        [215.3575, 378.3589, 281.5155, 425.3382],
        [ 44.7460, 369.1530, 479.2000, 639.2000],
        [140.0547, 384.9675, 219.9410, 460.2035],
        [272.8360, 463.6076, 375.6729, 551.9810],
        [148.5539, 483.5523, 253.6134, 571.3763],
        [ 71.0944, 376.3689, 269.5775, 550.3603],
        [266.1980, 192.0435, 383.7683, 332.7877],
        [220.4796, 425.3890, 305.4836, 505.9324],
        [  0.0000, 173.6925, 479.2000, 587.2295],
        [120.2271, 453.3583, 203.2584, 504.7998],
        [259.1699,  76.2862, 417.6064, 162.4225],
        [436.1358, 467.9624, 479.2000, 639.2000],
        [125.7446, 179.3962, 255.1829, 356.2068],
        [249.5824,  75.8131, 435.5853, 281.1515],
        [287.3286, 220.6237, 380.0404, 254.0769],
        [138.0458,   9.2817, 244.4318, 121.9354],
        [ 42.6394,   0.0000, 312.7134, 426.3010],
        [253.2154, 153.0676, 388.0854, 350.6571],


In [ ]:
print (spatial_adj_matrix)
print (spatial_adj_matrix.shape)

In [ ]:
print (semantic_adj_matrix)
print (semantic_adj_matrix.shape)

In [ ]:
dictionary = Dictionary.load_from_file(join('data', 'glove/dictionary.pkl'))
tfidf, weights = tfidf_from_questions_gqa(['test_all', 'val_all'], dictionary, 'data', 'gqa')

In [ ]:
a = np.random.randn(1, 1, 2, 3)

t1 = torch.tensor(a)
t2 = torch.tensor(a)
t3 = torch.tensor(a, device=torch.device('cpu'))
t1 = t3.to(torch.device('cpu'))

In [ ]:
device = torch.device("cpu")
print (device)