In [1]:
from dataset import Dictionary, VQAFeatureDataset, VisualGenomeFeatureDataset
from dataset_gqa import GQAFeatureDataset
from dataset_gqa import tfidf_from_questions_gqa
from os.path import join, exists
import torch
import numpy as np

In [2]:
dictionary = Dictionary.load_from_file(join('data', 'glove/dictionary.pkl'))
train_dset = GQAFeatureDataset('testdev_all', dictionary, 'semantic', adaptive=False, pos_emb_dim=64,dataroot='data')

loading dictionary from data/glove/dictionary.pkl
Initializing...
Loaded questions and answers for: testdev_all.
Loaded objects information.
Loaded spatial information.
Loaded spatial features.
Loaded object features.
Tokenization done.
Tensorized question and answers.
Tensorized spatial features.
Tensorized object features.
Intialized.


dictionary = Dictionary.load_from_file(join('data', 'glove/dictionary.pkl'))
train_dset = VQAFeatureDataset('train', dictionary, 'semantic', adaptive=False, pos_emb_dim=64,dataroot='data')

In [3]:
features, normalized_bb, question, target, question_id, image_id, bb, spatial_adj_matrix,semantic_adj_matrix = train_dset.__getitem__(10)

#{'question_id': 142001, 'image_id': 142, 'image': 6372, 'question': 'Is this a banana toast?', 'answer': {'labels': tensor([9, 3]), 'scores': tensor([1., 1.])}, 'q_token': tensor([    1,     2,    14,   352,   684, 19901, 19901, 19901, 19901, 19901,
#        19901, 19901, 19901, 19901])}

{'question_key': '201467614', 'question': 'Is the window cloudy?', 'image_id': 'n295771', 'answer': {'labels': tensor([0]), 'scores': tensor([1.])}, 'q_token': tensor([    1,    11,    40,  1348, 19901, 19901, 19901, 19901, 19901, 19901,
        19901, 19901, 19901, 19901])}
Object features not in memory. Loading...
Loaded object features.
Tensorized object features.
Spatial features not in memory. Loading...
Loaded spatial features.
Tensorized spatial features.


In [4]:
print (features)
print (features.shape)
#(100,2048)

tensor([[7.0172e-03, 4.8951e-01, 3.7418e-01,  ..., 0.0000e+00, 5.0612e-01,
         0.0000e+00],
        [7.4866e-04, 0.0000e+00, 1.6488e-01,  ..., 0.0000e+00, 2.2551e-03,
         0.0000e+00],
        [0.0000e+00, 1.1332e+00, 2.6261e-02,  ..., 3.6527e-01, 2.4187e-03,
         2.4918e-01],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])
torch.Size([100, 2048])


In [5]:
print (normalized_bb)
print (normalized_bb.shape)
#(2048,7,7)

tensor([[[0.0166, 0.1510, 0.1152,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.3483,  ..., 0.7187, 0.1777, 0.0000],
         [0.0000, 0.0000, 0.5946,  ..., 0.5334, 0.0000, 0.0000],
         ...,
         [0.0000, 0.2926, 1.1766,  ..., 1.8266, 0.0000, 0.0640],
         [0.2443, 1.0220, 2.2265,  ..., 1.4858, 0.0000, 0.0000],
         [0.3292, 0.7286, 1.1752,  ..., 1.0415, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0492, 0.0000,  ..., 0.5164, 0.0503, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.4921, 1.3259, 0.4958],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.1892, 0.3602, 0.4603],
         [0.0000, 0.0000, 0.0000,  ..., 0.0949, 0.0692, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.8802, 0.6113, 1.0594,  ..., 0.0000, 1.5388, 1.4326],
         [0.7975, 0.4723, 1.3067,  ..., 0.5121, 1.2779, 1.2546],
         [0.3376, 0.2295, 1.9661,  ..., 5.0621, 3.5765, 0.

In [7]:
numpy_array = np.zeros([2048,7])
for i in list(range(2048)):
    for j in list(range(7)):
        numpy_array[i][j] = (normalized_bb[i][j][0] + normalized_bb[i][j][1] + normalized_bb[i][j][2] +
                             normalized_bb[i][j][3] + normalized_bb[i][j][4] + normalized_bb[i][j][5] +
                             normalized_bb[i][j][6])/7
 
numpy_array = torch.from_numpy(numpy_array)

print (numpy_array)
print (numpy_array.shape)

tensor([[0.0734, 0.2176, 0.1998,  ..., 0.7388, 1.0544, 0.7815],
        [0.0000, 0.0920, 0.3305,  ..., 0.1442, 0.0234, 0.0000],
        [0.8943, 0.9562, 2.0511,  ..., 1.3823, 0.4246, 0.2461],
        ...,
        [0.0000, 0.0143, 0.4642,  ..., 0.8095, 0.5910, 0.3132],
        [1.0215, 1.2815, 1.2756,  ..., 0.5025, 0.8067, 0.9844],
        [1.0036, 1.1820, 0.7760,  ..., 0.2466, 0.3426, 0.2055]],
       dtype=torch.float64)
torch.Size([2048, 7])


In [ ]:
print (question)
print (question.shape)

In [ ]:
print (target)
print (target.shape)

In [ ]:
print (question_id)

In [ ]:
print (image_id)

In [ ]:
print (bb)
print (bb.shape)
#(100,4)

In [ ]:
print (spatial_adj_matrix)
print (spatial_adj_matrix.shape)

In [ ]:
print (semantic_adj_matrix)
print (semantic_adj_matrix.shape)

In [ ]:
dictionary = Dictionary.load_from_file(join('data', 'glove/dictionary.pkl'))
tfidf, weights = tfidf_from_questions_gqa(['test_all', 'val_all'], dictionary, 'data', 'gqa')

In [ ]:
a = np.random.randn(1, 1, 2, 3)

t1 = torch.tensor(a)
t2 = torch.tensor(a)
t3 = torch.tensor(a, device=torch.device('cpu'))
t1 = t3.to(torch.device('cpu'))

In [ ]:
device = torch.device("cpu")
print (device)